### ISSUE TITLE
Create example with persistent volumes

### ISSUE THREAD

**Issue by Jiri-Kremser** [radanalyticsio/spark-operator#154]
ssia

**Comment by reynoldsm88** [comment]
Is this a persistent volume for the history server using the `sharedVolume` tag? Or a shared file volume for data between master/worker?

**Comment by reynoldsm88** [comment]
@elmiko @Jiri-Kremser Am I on the right track [here](https://github.com/reynoldsm88/spark-operator/blob/14c1514f17d573f72d532a3afdbf1e13cb55b252/examples/cluster-persistent-volume.yaml) or wildly off target?

**Comment by Jiri-Kremser** [comment]
@reynoldsm88 this looks good

It's fine from the Kubernetes/OpenShift perspective. It would create durable data directory under `/etc/spark/data`. The data in it should survive the pod's restarts. Can you please also come up with some useful example from the Spark POV, where it would make sense such persistent volume? 

some ideas:

* In spark you can programmatically save/load RDDs or DataFrames from parquet or other formats so one possible example could be about storing/loading intermediate results explicitly.

* Another could be about event logs for spark itself, but this is captured by the HistoryServer use-case, I've done.

* If one calls `.(un)persist()` and the right `StorageLevel` is set, it stores the RDDs by default under `/tmp` 
( https://stackoverflow.com/a/30057925/1594980 ), so this could be another example (actually pretty similar to the first one).

* durable log files of spark master or workers


The ideal form would be probably some markdown file describing the use case.

**Comment by reynoldsm88** [comment]
@Jiri-Kremser something is wrong with that config. When I deploy that there are no errors and it looks like the PVC is created and the M/W containers come up fine. However, there is no `/opt/spark/mount` directory (I changed it because /etc has restricted permissions). Also, looking at the status of the mount after the deployment looks like it was never bound. Was that the write syntax for mounting that volume to the master/worker?

```bash
Michaels-MacBook-Pro-2:spark-operator michael$ oc get pvc
NAME                   STATUS    VOLUME                 CAPACITY   ACCESS MODES   STORAGECLASS   AGE
my-spark-cluster-pvc   Pending   my-spark-cluster-pvc   0                                        12m
```

**Comment by reynoldsm88** [comment]
I'll just post my current config here so no one has to hunt around for it:
```yaml
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-spark-cluster-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: my-spark-cluster-pvc

---
apiVersion: radanalytics.io/v1
kind: SparkCluster
metadata:
  name: cluster-with-shared-volume-2
spec:
  master:
    instances: "1"
    volumeMounts:
      mountPath: /etc/spark/data
      name: spark-data
  worker:
    instances: "2"
    volumeMounts:
      mountPath: /etc/spark/data
      name: spark-data
  volumes:
    name: spark-data
    persistentVolumeClaim:
        claimName: my-spark-cluster-pvc
```
