### ISSUE TITLE
Crd/cm for spark ui

### ISSUE THREAD

**Issue by Jiri-Kremser** [radanalyticsio/spark-operator#171]
By default the service/route for UI shouldn't be created. The service and route should be created on demand if user creates a new CR that can look like this for example:

```yaml
apiVersion: radanalytics.io/v1
kind: sparkui
metadata:
  name: my-spark-ui
spec:
  cluster: my-spark-cluster  # required -> no default
  port: xy                             # optional -> defaults to ..
  hostname: example.com  # optional -> no default 
```
