### ISSUE TITLE
Allow users to specify maven targets that will be added to spark container classpaths

### ISSUE THREAD

**Issue by elmiko** [radanalyticsio/spark-operator#213]
### Description:
in some cases it would be nice to have additional jar files added to the classpath for spark clusters upon boot. although there is the `downloadData` option in the schema, this is more oriented towards downloading user specific information (eg data files, etc).

i would like to propose we add a `mavenPackages` key to the schema that would contain a list of maven targets. these targets could then be downloaded and installed using an init container approach similar to the current download data targets.

i think this needs to be a separate key than `downloadData` as it uses a capability that requires more permission and specific mount points in the primary container.

#### example schema
```
apiVersion: radanalytics.io/v1
kind: SparkCluster
metadata:
  name: my-spark-cluster
spec:
  worker:
    instances: "2"
  master:
    instances: "1"
  mavenPackages:
  - org.apache.spark:spark-sql-kafka-0-10_2.11:2.3.0
  - org.apache.hadoop:hadoop-aws:2.7.3
```
