### ISSUE TITLE
Add a note to readme about integration with operator marketplace in 4.1

### ISSUE THREAD

**Issue by jkremser** [radanalyticsio/spark-operator#231]
```yaml
apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: radanalyticsio-operators
  namespace: openshift-marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: radanalyticsio
  displayName: "Operators from radanalytics.io"
  publisher: "Jirka Kremser"
```
