### ISSUE TITLE
custom labels for kube resources

### ISSUE THREAD

**Issue by Jiri-Kremser** [radanalyticsio/spark-operator#53]
labels are handy in K8s for querying the stuff, it would be nice to provide a way in the config maps or CRs to pass some custom key-value pairs and use them as labels on the resulting pods or replication controllers

**Comment by Jiri-Kremser** [comment]
desired behavior:

example CR:
```yaml
apiVersion: radanalytics.io/v1
kind: sparkcluster
metadata:
  name: my-spark-cluster
spec:
  worker:
    replicas: "2"
      labels:
        exampleLabelForAllTheWorkers/bar: foo
        label2: asdf
  master:
    replicas: "1"
    labels:
      exampleLabelForMaster/foo: bar
  labels:
    commonLabelForAllTheResourcesOperatorDeploys/deployedBy: John Doe
```

The labels in the `spec.labels` should be applied on all the resources we create in the K8s cluster, I.e. pods, services, RCs.

Those labels under `spec.{woker|master}.labels` should be applied only on the pods for worker or master.
