### ISSUE TITLE
master and worker section in the config maps

### ISSUE THREAD

**Issue by Jiri-Kremser** [radanalyticsio/spark-operator#79]
Currently there is `memory` and `cpu` that sets the (request)limits for pods, same value for workers and masters.. this should be decoupled.

instead of using:
```
masters: n
workers: m
masterMemory: X
masterCpu: x
workerMemory: Y
workerCpu: y
```

it would be better to have own section for master and for workers.. like in here:

```
master:
  count/replicas: n
  memory: X
  cpu: x
worker:
  count/replicas: m
  memory: Y
  cpu: y
```
